CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('student','parent','admin')), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS auth_sessions (token_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS student_profiles (student_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, grade integer NOT NULL DEFAULT 10 CHECK(grade BETWEEN 1 AND 12), age integer CHECK(age BETWEEN 5 AND 100), country text NOT NULL DEFAULT 'Ukraine', learning_language text NOT NULL DEFAULT 'en', interface_language text NOT NULL DEFAULT 'en', onboarded boolean NOT NULL DEFAULT false, xp integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS parent_profiles (parent_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS parent_student_links (parent_id text REFERENCES users(id) ON DELETE CASCADE, student_id text REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(parent_id,student_id));
CREATE TABLE IF NOT EXISTS parent_invites (token_hash text PRIMARY KEY, student_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS subjects (id text PRIMARY KEY, title jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS curricula (id text PRIMARY KEY, subject_id text NOT NULL REFERENCES subjects(id), title text NOT NULL, grade integer, cefr text CHECK(cefr IN ('A1','A2','B1','B2','C1')));
CREATE TABLE IF NOT EXISTS topics (id text PRIMARY KEY, curriculum_id text NOT NULL REFERENCES curricula(id), title jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS skills (id text PRIMARY KEY, subject_id text NOT NULL REFERENCES subjects(id), topic_id text NOT NULL REFERENCES topics(id), title jsonb NOT NULL, explanation jsonb NOT NULL, sort_order integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS skill_dependencies (skill_id text REFERENCES skills(id) ON DELETE CASCADE, prerequisite_id text REFERENCES skills(id) ON DELETE CASCADE, PRIMARY KEY(skill_id,prerequisite_id), CHECK(skill_id<>prerequisite_id));
CREATE TABLE IF NOT EXISTS questions (id text PRIMARY KEY, skill_id text NOT NULL REFERENCES skills(id) ON DELETE CASCADE, difficulty integer NOT NULL CHECK(difficulty BETWEEN 1 AND 3), prompt jsonb NOT NULL, options jsonb NOT NULL, answer integer NOT NULL CHECK(answer BETWEEN 0 AND 3), reasoning jsonb NOT NULL, hints jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS diagnostic_questions (question_id text PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS student_skill_mastery (id text PRIMARY KEY, student_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, skill_id text NOT NULL REFERENCES skills(id) ON DELETE CASCADE, mastery_score real NOT NULL DEFAULT 0 CHECK(mastery_score BETWEEN 0 AND 100), confidence_score real NOT NULL DEFAULT 0 CHECK(confidence_score BETWEEN 0 AND 1), attempts_count integer NOT NULL DEFAULT 0, correct_count integer NOT NULL DEFAULT 0, incorrect_count integer NOT NULL DEFAULT 0, hints_used integer NOT NULL DEFAULT 0, time_spent_seconds integer NOT NULL DEFAULT 0, last_practiced_at timestamptz, next_review_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(student_id,skill_id));
CREATE TABLE IF NOT EXISTS diagnostic_sessions (id text PRIMARY KEY, student_id text NOT NULL REFERENCES users(id), subject_id text NOT NULL REFERENCES subjects(id), state jsonb NOT NULL, completed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS diagnostic_answers (session_id text REFERENCES diagnostic_sessions(id), question_id text REFERENCES questions(id), correct boolean NOT NULL, answer integer NOT NULL, PRIMARY KEY(session_id,question_id));
CREATE TABLE IF NOT EXISTS lessons (id text PRIMARY KEY, skill_id text NOT NULL REFERENCES skills(id), title text NOT NULL);
CREATE TABLE IF NOT EXISTS lesson_steps (lesson_id text REFERENCES lessons(id), position integer NOT NULL, kind text NOT NULL, PRIMARY KEY(lesson_id,position));
CREATE TABLE IF NOT EXISTS lesson_sessions (id text PRIMARY KEY, student_id text NOT NULL REFERENCES users(id), skill_id text NOT NULL REFERENCES skills(id), state jsonb NOT NULL, completed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS student_answers (session_id text REFERENCES lesson_sessions(id), position integer NOT NULL, question_id text REFERENCES questions(id), answer integer NOT NULL, correct boolean NOT NULL, hints integer NOT NULL DEFAULT 0, PRIMARY KEY(session_id,position));
CREATE TABLE IF NOT EXISTS learning_events (id text PRIMARY KEY, student_id text NOT NULL REFERENCES users(id), skill_id text NOT NULL REFERENCES skills(id), kind text NOT NULL, before_score real NOT NULL, after_score real NOT NULL, seconds integer NOT NULL, xp integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS learning_events_owner_time ON learning_events(student_id,created_at);
CREATE INDEX IF NOT EXISTS mastery_owner_review ON student_skill_mastery(student_id,next_review_at);
CREATE INDEX IF NOT EXISTS questions_skill ON questions(skill_id,difficulty);
CREATE INDEX IF NOT EXISTS parent_link_student ON parent_student_links(student_id);
CREATE TABLE IF NOT EXISTS daily_plans (student_id text REFERENCES users(id), day date NOT NULL, plan jsonb NOT NULL, PRIMARY KEY(student_id,day));
CREATE TABLE IF NOT EXISTS weekly_reports (student_id text REFERENCES users(id), week date NOT NULL, report jsonb NOT NULL, PRIMARY KEY(student_id,week));
CREATE TABLE IF NOT EXISTS ai_prompts (id text PRIMARY KEY, content text NOT NULL);
CREATE TABLE IF NOT EXISTS ai_interactions (id text PRIMARY KEY, student_id text REFERENCES users(id), method text NOT NULL, provider text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS speaking_sessions (id text PRIMARY KEY, student_id text NOT NULL REFERENCES users(id), mode text NOT NULL, topic text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS speaking_turns (id text PRIMARY KEY, session_id text NOT NULL REFERENCES speaking_sessions(id), transcript text NOT NULL, feedback jsonb NOT NULL, reply text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audio_records_metadata (id text PRIMARY KEY, session_id text NOT NULL REFERENCES speaking_sessions(id), bytes integer NOT NULL, mime text NOT NULL, source_deleted boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE speaking_sessions ADD COLUMN IF NOT EXISTS completed boolean NOT NULL DEFAULT false;
CREATE TABLE IF NOT EXISTS schema_migrations (id text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE learning_events ADD COLUMN IF NOT EXISTS event_order bigserial;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS timezone text NOT NULL DEFAULT 'Europe/Kyiv';
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS daily_minutes integer NOT NULL DEFAULT 25 CHECK(daily_minutes BETWEEN 10 AND 90);
CREATE TABLE IF NOT EXISTS student_subjects(student_id text REFERENCES users(id) ON DELETE CASCADE, subject_id text REFERENCES subjects(id), active boolean NOT NULL DEFAULT true, started_at timestamptz NOT NULL DEFAULT now(), paused_at timestamptz, PRIMARY KEY(student_id,subject_id));
CREATE INDEX IF NOT EXISTS student_subjects_active ON student_subjects(student_id) WHERE active;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS strand_id text;
ALTER TABLE student_skill_mastery ADD COLUMN IF NOT EXISTS independent_count integer NOT NULL DEFAULT 0;
ALTER TABLE student_skill_mastery ADD COLUMN IF NOT EXISTS evidence_days integer NOT NULL DEFAULT 0;
ALTER TABLE student_skill_mastery ADD COLUMN IF NOT EXISTS retention_count integer NOT NULL DEFAULT 0;
ALTER TABLE student_skill_mastery ADD COLUMN IF NOT EXISTS long_retention_count integer NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS skill_evidence(id text PRIMARY KEY, student_id text REFERENCES users(id), skill_id text REFERENCES skills(id), session_id text NOT NULL, question_id text NOT NULL, correct boolean NOT NULL, independent boolean NOT NULL, local_day date NOT NULL, retained boolean NOT NULL, long_retained boolean NOT NULL, before_state jsonb NOT NULL, after_state jsonb NOT NULL, created_at timestamptz NOT NULL, UNIQUE(student_id,session_id,question_id));
CREATE INDEX IF NOT EXISTS evidence_owner_skill_time ON skill_evidence(student_id,skill_id,created_at);
ALTER TABLE skill_evidence ADD COLUMN IF NOT EXISTS evidence_order bigserial;
ALTER TABLE learning_events ADD COLUMN IF NOT EXISTS session_id text;
ALTER TABLE learning_events ADD COLUMN IF NOT EXISTS evidence_id text;
CREATE TABLE IF NOT EXISTS ai_requests(id text PRIMARY KEY, student_id text REFERENCES users(id), session_id text, kind text NOT NULL, result jsonb, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE skills ADD COLUMN IF NOT EXISTS review_status text NOT NULL DEFAULT 'draft' CHECK(review_status IN ('draft','reviewed','approved'));
ALTER TABLE questions ADD COLUMN IF NOT EXISTS review_status text NOT NULL DEFAULT 'draft' CHECK(review_status IN ('draft','reviewed','approved'));
CREATE TABLE IF NOT EXISTS pilot_consent(student_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,parent_id text REFERENCES users(id) ON DELETE SET NULL,version text NOT NULL,granted boolean NOT NULL,allow_speaking boolean NOT NULL DEFAULT false,granted_at timestamptz,withdrawn_at timestamptz);
CREATE TABLE IF NOT EXISTS consent_history(id bigserial PRIMARY KEY,student_id text REFERENCES users(id) ON DELETE CASCADE,parent_id text REFERENCES users(id) ON DELETE SET NULL,version text NOT NULL,granted boolean NOT NULL,allow_speaking boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS pilot_events(id text PRIMARY KEY,user_id text REFERENCES users(id) ON DELETE CASCADE,event text NOT NULL,subject_id text,session_id text,dedupe text NOT NULL,seconds integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,event,dedupe));
CREATE INDEX IF NOT EXISTS pilot_events_time ON pilot_events(created_at,event);
CREATE TABLE IF NOT EXISTS pilot_feedback(user_id text REFERENCES users(id) ON DELETE CASCADE,screen text NOT NULL,context_id text NOT NULL,rating text NOT NULL CHECK(rating IN ('up','neutral','down')),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,screen,context_id));
INSERT INTO schema_migrations(id) VALUES('pilot-v3') ON CONFLICT DO NOTHING;
