import { it, expect } from 'vitest';
import { createDB, transaction } from '../server/db';
import { seed } from '../server/seed';
import { evidence } from '../server/domain';
import { masteryStatus } from '../shared/learning';
import { writeFile } from 'node:fs/promises';
it('reproduces the documented 44-point progression across sessions and spaced checks', async () => {
  const db = await createDB('memory://');
  await seed(db);
  try {
    await db.query(
      "UPDATE student_skill_mastery SET mastery_score=44,confidence_score=.15 WHERE student_id='demo-student' AND skill_id='quadratic'",
    );
    const rows: any[] = [];
    for (const [i, day] of [0, 2, 5, 12, 19, 26, 33].entries()) {
      for (let q = 0; q < 3; q++)
        await transaction(db, () =>
          evidence(
            db,
            'demo-student',
            'quadratic',
            true,
            0,
            60,
            'answer',
            'example-session-' + i,
            'quadratic-' + ((i * 3 + q) % 9),
            new Date(Date.UTC(2026, 8, 1 + day, 10)),
          ),
        );
      const m = (
        await db.query(
          "SELECT * FROM student_skill_mastery WHERE student_id='demo-student' AND skill_id='quadratic'",
        )
      ).rows[0];
      rows.push({
        day,
        score: m.mastery_score,
        confidence: Math.round(m.confidence_score * 100),
        independent: m.independent_count,
        retention: m.retention_count,
        status: masteryStatus(m),
      });
    }
    expect(rows.map((r) => r.score)).toEqual([52, 60, 68, 76, 84, 92, 100]);
    expect(rows[0].retention).toBe(0);
    expect(rows[4].status).toBe('mastered');
    expect(rows[6].status).toBe('strong');
    if (process.env.WRITE_PROGRESSION === 'true')
      await writeFile(
        'docs/PROGRESSION.md',
        '# Reproducible progression example\n\nGenerated by tests/progression.test.ts with an isolated in-memory database. Starting score 44, legacy confidence 15%, no fabricated retention. Three correct independent responses per session; nine distinct question IDs rotated across sessions. This is a deterministic example, not a prediction or guaranteed learning outcome.\n\n| Day | Score estimate | Confidence | Distinct independent questions | Spaced checks | Status |\n| --- | --- | --- | --- | --- | --- |\n' +
          rows
            .map(
              (r) =>
                `| ${r.day} | ${r.score} | ${r.confidence}% | ${r.independent} | ${r.retention} | ${r.status} |`,
            )
            .join('\n') +
          '\n\nOne session changes 44 → 52, not 80–90. Strong is possible only after multiple days, sufficient distinct evidence and delayed successful checks including a 7-day gap. Questions with hints, mistakes, repeated IDs and same-day sessions produce different results.\n',
      );
  } finally {
    await db.close();
  }
});
